api_hash: a9a02c1d67d1fffc9f99b033fbbda44a
api_id: 28138839
chat:
- chat_id: -1002090605054
  last_read_message_id: 16197
file_formats:
  # audio:
  # - all
  # document:
  # - all
  video:
  - all
file_path_prefix:
- chat_title
- media_datetime
media_types:
# - audio
# - photo
- video
# - document
# - voice
# - video_note
# in linux please use /
# save_path: E:\github\telegram_media_downloader
save_path: C:\Users\wf\Documents\telegram_media_downloader\downloads
language: EN
